### ISSUE TITLE
SSL error with optimizely

### ISSUE THREAD

**Issue by abiodunjames** [optimizely/python-sdk#316]
I'm currently trying to integrate with optimizely from a backend code.  I get this error which causes the application to fail
``` python

Fetching datafile from https://cdn.optimizely.com/datafiles/XXXXXXXXXXX.json failed. Error: 

HTTPSConnectionPool(host='cdn.optimizely.com', port=443): Max retries exceeded with url:
 /datafiles/VhiH4avQ1x9uYuEGumBvf.json (Caused by SSLError(SSLError(1, '
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

```

Using version `optimizely-sdk = "^3.8.0"`

**Comment by abiodunjames** [comment]
There is a bug in the requests library greater than `2.24.0`. Optimizely uses requests to fetch datafile from its server; this bug in the requests breaks Optimizely. It's hard to debug. We fixed this by installing requests and pinning its version at `2.24.0`
More details on this bug can be found here. https://github.com/psf/requests/issues/5703

**Comment by msohailhussain** [comment]
The actual discussion is inside this thread. 
https://github.com/urllib3/urllib3/issues/2075
Closing it, since it's not an issue in OptimizelySDK.
