### ISSUE TITLE
raise exception when validating datafile and datafile is not valid

### ISSUE THREAD

**Issue by zhammer** [optimizely/python-sdk#376]
would it be possible to send an exception to the error handler when schema validation is enabled but the datafile provided is not valid? current behavior is log error but continue as is.

https://github.com/optimizely/python-sdk/blob/b6c2c63589c3bf7c52d863cab7f7858f919eff3d/optimizely/config_manager.py#L104-L107

**Comment by Mat001** [comment]
Thank you @zhammer . Looking into it.
There may be considerations around consistency inside Py sdk as well with other SDKs.
Also how expensive the change would be, also seems like that would be an API change.

**Comment by Mat001** [comment]
@zhammer My assumption is that you would like to be informed in real time if datafile validation failed?
Yes, you can set the logger to show the error, but that's not in real time.

You could use Decide API in the SDK to display reasons. We return null variation and error message in real-time (in reasons when config fails).
For example set options = [DecideOption.INCLUDE_REASONS] and then call reasons on your decision like so decision.reasons.
You should get the error message: 'Optimizely SDK not configured properly yet.'
Would that work?

Changing log error to raising an exception would unfortunately be a breaking change for the API which is a significant task for the moment.
