### ISSUE TITLE
Feature "my_feature" is not in datafile.

### ISSUE THREAD

**Issue by christianbundy** [optimizely/python-sdk#400]
We have many features that are set to 'off' in production, which have historically been included in the datafile. Today, these features went missing from the datafile, which seems to have started logging tons of "Feature "my_feature" is not in datafile." error. This was very surprising, and the increased rate of error logs caused alerts to be sent to engineers.

Our temporary solution: find all flags where production is set to 'off' and change it to 'on' and '0%'. This seems to be a distinction without a difference, but it makes the torrent of error messages go away.

We're on the latest Optimizely SDK version, and haven't upgraded recently, which leads me to believe that this was a back-end change. Was this intended to cause errors, or was this a bug in the Python SDK?

**Comment by andrewleap-optimizely** [comment]
@christianbundy thanks for bringing this to our attention!

This was indeed a back-end change. We have implemented a fix and now the feature flags set to 'off' should be included in the datafile again. Let us know if this resolves the issue for you.

**Comment by christianbundy** [comment]
Cool, it sounds like this is unrelated to the Python SDK and has already been resolved. Thanks for the quick response here.
