### ISSUE TITLE
adding a variation will change how existing users are allocated to their variations

### ISSUE THREAD

**Issue by jondot** [optimizely/python-sdk#49]
Hi,
According to this implementation, adding a variation to a running experiment will change how existing users are allocated to their variations.
How can that be fixed?

Thanks

**Comment by aliabbasrizvi** [comment]
Hi @jondot 

I am assuming the preference is that when a new variation is added, then existing users continue seeing the variation that they originally saw. We have user profiles in our Android/iOS SDKs: https://developers.optimizely.com/x/solutions/sdks/reference/?language=android#profiles and are actively working on making the interface available in our Python SDK. I am hopeful it will be ready in the coming week.

Thanks

**Comment by aliabbasrizvi** [comment]
@jondot user profiles are not available and should address this. Documentation here: https://developers.optimizely.com/x/solutions/sdks/reference/?language=python#profiles. Closing out this issue. Please feel free to re-open if this is not what you are looking for.
