### ISSUE TITLE
When will support for user profiles be added?

### ISSUE THREAD

**Issue by evasilchenko** [optimizely/python-sdk#51]
I just read that **user profiles** for the backend-sdk is not currently supported and that sdk consumers are required to roll their own variation stickiness.

https://developers.optimizely.com/x/solutions/sdks/reference/index.html?language=python#profiles

I am wondering if/when this support is planned to be added to the SDK as we are currently evaluating the implementation of optimizely within our platform? I think this question is also related to: https://github.com/optimizely/python-sdk/issues/49

Thank you and looking forward to your response.

**Comment by aliabbasrizvi** [comment]
@evasilchenko we are actively working on user profiles for Python SDK and will hopefully have the interface out in the coming week.

**Comment by evasilchenko** [comment]
@aliabbasrizvi That's really great to know. Thank you for the response and looking forward to it.

**Comment by aliabbasrizvi** [comment]
@evasilchenko user profiles is available now. Documentation here: https://developers.optimizely.com/x/solutions/sdks/reference/?language=python#profiles. Closing out this issue. Please feel free to open another issue if you have questions about user profile.

**Comment by evasilchenko** [comment]
@aliabbasrizvi thank you for including this in the sdk. I think I misunderstood the work that will be done. With what is currently built, we are still required to host user profiles somewhere in our system as opposed to optimizely being the system of record. So optimizely never hosts user profiles in their system or is this a limitation of the python sdk?

**Comment by aliabbasrizvi** [comment]
Hi @evasilchenko , we are not planning to host user profiles at the moment. That is a limitation of our Python SDK as well as other server side SDKs that we have i.e. Java, Node, Ruby, PHP and C#. We are currently looking into how to tackle that at scale for our customers. In the meanwhile, we do recognize this to be an important feature and so you can implement the interface so that your use case is achieved.
