### ISSUE TITLE
python 3.5 and 3.6 support?

### ISSUE THREAD

**Issue by jeduden** [optimizely/python-sdk#64]
do you support python 3.5 and python 3.6 ?

**Comment by aliabbasrizvi** [comment]
Hi @jeduden ... thanks for reaching out. Looks like Python 3.5 and Python 3.6 will be fine. See Travis report here: https://travis-ci.org/optimizely/python-sdk/builds/260471069

**Comment by aliabbasrizvi** [comment]
@jeduden please re-open in case of any other question.
